#http://docs.ansible.com/ansible/playbooks_variables.html#variable-file-separation
---
- hosts: web
  sudo: yes
  gather_facts: no
  remote_user: vagrant
  vars_files:
    - myvars

  tasks:

  - name: Move config
    template: src=template.j2 dest=/etc/merge

