# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # create mgmt node
  config.vm.define :mgmt do |mgmt_config|
      mgmt_config.vm.box = "ubuntu/trusty32"
      mgmt_config.vm.hostname = "ub14"
      mgmt_config.vm.network :private_network, ip: "10.0.15.10"
      mgmt_config.vm.network "forwarded_port", guest: 3306, host: "4444"
      mgmt_config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
      end
      mgmt_config.vm.provision :shell, path: "bootstrap.sh"
  end
end
