---
- name: Ensure HAProxy is installed (Debian).
  apt: name=haproxy=1.4.24-2ubuntu0.4 state=installed 
  when: ansible_os_family == 'Debian'

- name: Ensure HAProxy is enabled (so init script will start it on Debian).
  lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED.+$"
    line: "ENABLED=1"
    state: present
  when: ansible_os_family == 'Debian'

- name: Copy HAProxy configuration in place.
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy

- name: Copy HAProxy log configuration
  template:
    src: loghaproxy.conf.j2
    dest: /etc/rsyslog.d/haproxy.conf
    mode: 0644
  notify: restart rsyslog

- name: Ensure HAProxy is started and enabled on boot.
  service: name=haproxy state=started enabled=yes
