---
haproxy_stats_port: 9000
haproxy_chroot: /var/lib/haproxy
haproxy_user: haproxy
haproxy_group: haproxy
haproxy_log_path: /var/log/haproxy_1.log 

# Frontend settings.
haproxy_frontend_name: 'hafrontend'
haproxy_frontend_bind_address: '*'
haproxy_frontend_port: 8081
haproxy_frontend_mode: 'http'

# Backend settings.
haproxy_backend_name: 'habackend'
haproxy_backend_mode: 'http'
haproxy_backend_balance_method: 'roundrobin'
haproxy_backend_httpchk: 'HEAD / HTTP/1.1\r\nHost:localhost'
haproxy_backend_timeout_client: 5000

#stats settings:
haproxy_stats_username: 'test'
haproxy_stats_password: 'test'

# List of backend servers.
haproxy_backend_servers: 
   - name: app1
     address: 127.0.0.1:80
  # - name: app2
  #   address: 192.168.0.2:80

# Extra global vars (see README for example usage).
haproxy_global_vars: []
